export const MUTE = 'MUTE';
export const MUTE_ALL = 'MUTE_ALL';
export const SPACE_NAME = 'SPACE_NAME';

export const ADD_LOCAL_TRACK = 'ADD_LOCAL_TRACK';
export const UPDATE_LOCAL_TRACK = 'UPDATE_LOCAL_TRACK';
export const REMOVE_LOCAL_TRACK = 'REMOVE_LOCAL_TRACK';
export const LOCAL_TRACK_ACTION = 'LOCAL_TRACK_ACTION';

export const ADD_CONFERENCE = 'ADD_CONFERENCE';
export const ADD_CONNECTION = 'ADD_CONNECTION';
export const REMOVE_CONFERENCE = 'REMOVE_CONFERENCE';
export const GET_CONFERENCE = 'GET_CONFERENCE';

export const CREATE_LOCAL_TRACKS = 'CREATE_LOCAL_TRACKS';
export const REMOVE_CONNECTION = 'REMOVE_CONNECTION';

//connection
export const CONNECTION_ESTABLISHED = 'CONNECTION_ESTABLISHED';
export const CONNECTION_DISCONNECTED = 'CONNECTION_DISCONNECTED';
export const CONNECTION_FAILED = 'CONNECTION_FAILED';

// confernece
export const CONFERENCE_JOINED = 'CONFERENCE_JOINED';
export const CONFERENCE_LEFT = 'CONFERENCE_LEFT';
export const CONFERENCE_FAILED = 'CONFERENCE_FAILED';
export const CONFERENCE_ERROR = 'CONFERENCE_ERROR';

// track
export const TRACK_ADDED = 'TRACK_ADDED';
export const TRACK_REMOVED = 'TRACK_REMOVED';
export const TRACK_MUTE_CHANGED = 'TRACK_MUTE_CHANGED';

export const CONNECTION_DISCONNECT = 'disconnect';

export const REMOVE_ALL_LOCAL_TRACK = 'REMOVE_ALL_LOCAL_TRACK';
export const PASSWORD_REQUIRED = 'PASSWORD_REQUIRED';

export const LOCAL_TRACK_MUTE_CHANGED = 'LOCAL_TRACK_MUTE_CHANGED';
export const SELECT_PARTICIPANT = 'SELECT_PARTICIPANT';

export const ADD_REMOTE_TRACK = 'ADD_REMOTE_TRACK';
export const UPDATE_REMOTE_TRACK = 'UPDATE_REMOTE_TRACK';
export const REMOVE_REMOTE_TRACK = 'REMOVE_REMOTE_TRACK';
export const REMOVE_ALL_REMOTE_TRACK = 'REMOVE_ALL_REMOTE_TRACK';
export const REMOTE_TRACK_MUTE_CHANGED = 'REMOTE_TRACK_MUTE_CHANGED';

export const SET_LAYOUT = 'SET_LAYOUT';
export const SET_FULLSCREEN_MODE = 'SET_FULLSCREEN_MODE';
export const CLEAR_ALL = 'CLEAR_ALL';
export const SET_ACTIVE_CONTROL = 'SET_ACTIVE_CONTROL';

export const SET_PROFILE = 'SET_PROFILE';
export const ADD_MESSAGE = 'ADD_MESSAGE';

export const SET_MICROPHONE = 'SET_MICROPHONE';
export const SET_SPEAKER = 'SET_SPEAKER';
export const SET_RESOLUTION = 'SET_RESOLUTION';
export const SET_CAMERA = 'SET_CAMERA';

export const UNREAD_MESSAGES = 'UNREAD_MESSAGES';
export const SET_PIN_PARTICIPANT = 'SET_PIN_PARTICIPANT';
export const SET_PRESENTER = 'SET_PRESENTER';
export const ADD_COLOR = 'ADD_COLOR';
export const REMOVE_COLOR = 'REMOVE_COLOR';
export const SET_AUDIO_LEVEL = 'SET_AUDIO_LEVEL';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';

export const SET_GOOGLE_API_STATE = 'SET_GOOGLE_API_STATE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const SET_DISCONNECTED = 'SET_DISCONNECTED';

export const SET_PRESENTATION_TYPE = 'SET_PRESENTATION_TYPE';
export const SET_HAND_RAISE = 'SET_HAND_RAISE';

//space
export const SET_SPACE_TITLE = 'SET_SPACE_TITLE';
export const START_SPACE = 'START_SPACE';
export const END_SPACE = 'END_SPACE';
export const SET_HOST = 'SET_HOST';
export const TRANSFER_HOST = 'TRANSFER_HOST';
export const SET_CO_HOST = 'SET_CO_HOST';
export const REMOVE_CO_HOST = 'REMOVE_CO_HOST';
export const MAKE_SPEAKER = 'MAKE_SPEAKER';
export const REMOVE_SPEAKER = 'REMOVE_SPEAKER';
export const MAKE_LISTENER = 'MAKE_LISTENER';
export const SELECT_PARTICIPANT_TYPE = 'SELECT_PARTICIPANT_TYPE';
export const SET_SPACE_TYPE = 'SET_SPACE_TYPE';
export const SET_SUB_ROLE = 'SET_SUB_ROLE';
export const USER_ROLE_CHANGED = 'USER_ROLE_CHANGED';

export const ADD_PARTICIPANT = 'ADD_PARTICIPANT';
export const REMOVE_PARTICIPANT = 'REMOVE_PARTICIPANT';
export const PARTICIPANT_PROPERTY_CHANGED = 'PARTICIPANT_PROPERTY_CHANGED';
export const UPDATE_LOCAL_PARTICIPANT_SUB_ROLE =
  'UPDATE_LOCAL_PARTICIPANT_SUB_ROLE';
export const SET_NAME = 'SET_NAME';
